version: "3.7"
services:
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes:
            - cache:/data
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ScalableProgramming
            MONGO_INITDB_ROOT_PASSWORD: ygAb4yG2cgdQBxvhyhWf33MV
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongodb-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ScalableProgramming
            ME_CONFIG_MONGODB_ADMINPASSWORD: ygAb4yG2cgdQBxvhyhWf33MV
            ME_CONFIG_MONGODB_URL: mongodb://ScalableProgramming:ygAb4yG2cgdQBxvhyhWf33MV@mongo:27017/
        depends_on:
            - mongo

volumes:
    cache:
        driver: local
    mongodb_data_container:
